// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eopsxqyssnmvebdpilyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvcHN4cXlzc25tdmViZHBpbHlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MDEyNTYsImV4cCI6MjA2OTQ3NzI1Nn0.hpws8pyv1hPtfyv2ynJo_f5_d5UlIKaSodXeI4a9VoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});